import { GoogleGenAI } from '@google/genai';
import { AIFeatureConfig, KankaSearchResult } from '../types/audio-session.types';
import { SESSION_STORY_GENERATOR_PROMPT } from '../prompts/session-story-generator.prompt';

/**
 * Generates a story from transcription using AI
 *
 * @param transcription - Full transcription text with timestamps
 * @param sessionTitle - Title of the session for context
 * @param sessionDate - Date of the session (optional)
 * @param config - AI model configuration
 * @param kankaContext - Optional campaign context for accuracy
 * @param userCorrections - Optional DM corrections to apply
 * @returns Generated story content
 */
export async function generateStoryFromTranscription(
  transcription: string,
  sessionTitle: string,
  sessionDate: string | undefined,
  config: AIFeatureConfig,
  kankaContext?: KankaSearchResult,
  userCorrections?: string
): Promise<string> {
  const googleAiKey = process.env.GOOGLE_AI_API_KEY;
  if (!googleAiKey) {
    throw new Error('Google AI API key not configured');
  }

  const googleAi = new GoogleGenAI({ apiKey: googleAiKey });

  console.log(`Generating story with ${config.model}...`);

  const storyPrompt = buildStoryPrompt(transcription, kankaContext, userCorrections);

  const storyResponse = await googleAi.models.generateContent({
    model: config.model,
    contents: [{ role: 'user', parts: [{ text: storyPrompt }] }],
    config: {
      temperature: config.temperature,
      topP: config.topP,
      topK: config.topK,
      maxOutputTokens: config.maxOutputTokens
    }
  });

  if (!storyResponse.text) {
    throw new Error('No story generated by AI');
  }

  const storyContent = storyResponse.text.trim();

  console.log(`Story generated: ${storyContent.length} characters`);

  return storyContent;
}

/**
 * Builds story generation prompt with context and corrections
 */
function buildStoryPrompt(
  transcription: string,
  kankaContext?: KankaSearchResult,
  userCorrections?: string
): string {
  let prompt = SESSION_STORY_GENERATOR_PROMPT;

  if (kankaContext && Object.keys(kankaContext).length > 0) {
    const contextPrompt = buildKankaContextPrompt(kankaContext);
    prompt += `\n\n${contextPrompt}`;
  }

  if (userCorrections && userCorrections.trim().length > 0) {
    prompt += `\n\nDM CORRECTIONS:\n${userCorrections}`;
  }

  prompt += `\n\nSESSION TRANSCRIPT:\n${transcription}`;

  return prompt;
}

/**
 * Formats Kanka context for prompt injection
 */
function buildKankaContextPrompt(context: KankaSearchResult): string {
  const sections: string[] = [];

  const addSection = (
    label: string,
    entities: Array<{ name: string; entry?: string; entry_parsed?: string }> | undefined
  ) => {
    if (!entities?.length) {
      return;
    }
    const names = entities.map(entity => entity.name).join(', ');
    sections.push(`${label}: ${names}`);
  };

  addSection('Characters', context.characters);
  addSection('Locations', context.locations);
  addSection('Quests', context.quests);
  addSection('Organisations', context.organisations);

  if (sections.length === 0) {
    return '';
  }

  return `CAMPAIGN REFERENCE (for name/place accuracy only):
${sections.join('\n')}

Remember: Use this context ONLY to spell names and places correctly when you hear them. Do not add information that wasn't spoken.`;
}
